#!/usr/bin/ash

emergency_console() {
    echo "WARNING: an error has occured, launching an emergency console."
    export PS1='[rootfs \W]\$ '
    exec sh -i
}

# Retrieve cryptdevice name from boot cmdline
cryptname=$(sed -n 's/.*cryptdevice=[^: ]*:\([^: ]*\).*$/\1/p' /proc/cmdline)

# Suspend root device
[ -z "${cryptname}" ] || cryptsetup luksSuspend "${cryptname}"

# Suspend the system
echo mem > /sys/power/state

# Resume root device
[ -z "${cryptname}" ] || cryptsetup luksResume "${cryptname}" || emergency_console
