#!/usr/bin/ash

cryptname="${1}"

panic() { while :; do echo o > /proc/sysrq-trigger; done }

# Start udev from initramfs
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never

# Suspend root device, else shutdown
cryptsetup luksSuspend "${cryptname}" || panic

# Suspend the system
echo mem > /sys/power/state

# Resume root device, else shutdown
cryptsetup luksResume "${cryptname}" || panic

# Stop udev from initramfs, as the real daemon from rootfs will be restarted
udevadm control --exit
